package tony;

import javafx.geometry.Pos;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Priority;
import javafx.scene.layout.Region;

/**
 * Displays one user or Tony message as a chat bubble.
 */
public class DialogBox extends HBox {
    /** Width reserved around a message so its bubble remains easy to read. */
    private static final double MESSAGE_SIDE_SPACE = 88;

    private DialogBox(String message, String speaker, boolean isUser) {
        Label speakerLabel = new Label(speaker);
        speakerLabel.getStyleClass().add("speaker-label");

        Label messageLabel = new Label(message);
        messageLabel.setWrapText(true);
        messageLabel.setMinHeight(Region.USE_PREF_SIZE);
        messageLabel.setMaxWidth(Double.MAX_VALUE);
        messageLabel.getStyleClass().add(isUser ? "user-bubble" : "tony-bubble");

        Region spacer = new Region();
        HBox.setHgrow(spacer, Priority.ALWAYS);
        HBox.setHgrow(messageLabel, Priority.ALWAYS);
        messageLabel.maxWidthProperty().bind(widthProperty().subtract(MESSAGE_SIDE_SPACE));

        setAlignment(Pos.TOP_LEFT);
        setSpacing(10);
        getStyleClass().add("dialog-box");
        if (isUser) {
            setAlignment(Pos.TOP_RIGHT);
            getChildren().addAll(spacer, messageLabel, speakerLabel);
        } else {
            getChildren().addAll(speakerLabel, messageLabel, spacer);
        }
    }

    /**
     * Creates a message displayed on the user's side of the conversation.
     *
     * @param message message entered by the user.
     * @return the user dialog box.
     */
    public static DialogBox getUserDialog(String message) {
        return new DialogBox(message, "You", true);
    }

    /**
     * Creates a message displayed on Tony's side of the conversation.
     *
     * @param message response generated by Tony.
     * @return Tony's dialog box.
     */
    public static DialogBox getTonyDialog(String message) {
        return new DialogBox(message, "T", false);
    }
}
